<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Sprint;

/**
 * SprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SprintRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Sprint[]
     */
    public function getAllAsArray()
    {
        $qb = $this->createQueryBuilder('s');
        $qb->select('s.id, s.name, s.created');

        $sprints = $qb->getQuery()->getArrayResult();

        foreach ($sprints as $index => $sprint) {
            $sprints[$index]['created'] = $sprints[$index]['created']->format('d/m/Y');
        }

        return $sprints;
    }

    /**
     * @return Sprint
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getCurrentSprint()
    {
        $qb = $this->createQueryBuilder('s');
        $qb
            ->setMaxResults(1)
            ->orderBy('s.created', 'desc')
        ;

        return $qb->getQuery()->getSingleResult();
    }
}
